version: 0.0
os: linux
files:
  - source: /build/
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: |
        # Install Nginx and Node.js
        sudo yum update -y
        sudo yum install -y nginx
        sudo yum install -y nodejs npm
        
  ApplicationStart:
    - location: |
        # Copy React build files to the default Nginx directory
        sudo cp -r /var/www/html/* /usr/share/nginx/html/
        sudo systemctl restart nginx
