version: 0.0
os: linux
files:
  - source: /build/
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      runas: root
  AfterInstall:
    - location: start_server.sh
      runas: root
